export const GET_HOST_POST_LIST = "GET_HOST_POST_LIST";
export const GET_HOST_POST_LIST_SUCCEED = "GET_HOST_POST_LIST_SUCCEED";
export const GET_ROOM_DETAIL = "GET_ROOM_DETAIL";
export const GET_ROOM_DETAIL_SUCCEED = "GET_ROOM_DETAIL_SUCCEED";
export const POST_POST = "POST_POST";
export const POST_FAVORITE = "POST_FAVORITE";
export const SEARCH_POST = "SEARCH_POST";
