export const GET_RENTER_PROFILE = "GET_RENTER_PORFILE";
export const GET_HOST_PROFILE = "GET_HOST_PORFILE";
export const PUT_RENTER_UPDATE_PROFILE = "PUT_RENTER_UPDATE_PROFILE";
export const PUT_HOST_UPDATE_PROFILE = "PUT_HOST_UPDATE_PROFILE";
export const PUT_CHANGE_PASSWORD = "PUT_CHANGE_PASSWORD";
